### ISSUE TITLE
Meta data for links

### ISSUE THREAD

**Issue by ohedwall** [newsvoice/newsvoice#1]
When submitting a link to social media, such as Facebook, both headline and short desc is based on Newsvoice title:
![image](https://cloud.githubusercontent.com/assets/14863888/26682078/8100e9bc-46df-11e7-9b6a-4fbccfbdb2aa.png)

Short desc should be based on Newsvoice summary, if it exists.

**Comment by ohedwall** [comment]
Also, remove "Newsvoice:" in the headline so it is easier to see the whole headline and be more likely to click it

**Comment by vlidholt** [comment]
This is fixed
