### ISSUE TITLE
Better commenting guidelines

### ISSUE THREAD

**Issue by vlidholt** [newsvoice/newsvoice#153]
Make more clear guidelines for moderation.

**Comment by frog712** [comment]
What exactly do you mean by this?

**Comment by vlidholt** [comment]
This is now implemented in the app, loading the text from server so it can be changed. Text is still not finalized.

@frog712 We are clarifying the rules for how to moderate comments, on what to hide, and what to remove. We only remove things we are required to remove by law, we hide things that are breaking App Store and Google Play rules.

**Comment by vlidholt** [comment]
Online on the web, will be part of the next app update
