### ISSUE TITLE
Troubleshoot: Name attribution on a summary that is edited.

### ISSUE THREAD

**Issue by BreakingBubbles** [newsvoice/newsvoice#177]
Not a very usual flow but could happen more with more volunteer action. In this case:
- User "A" wrote a summary. Summary is approved
- User "B" made some edits of what he thought to be factually incorrect. 
- Changes are approved. User "B" gets his name under the summary. 
- User "B" makes further edits to his summary to correct a typo. 
- Summary is rejected. No re-submission.
- The summary on the story changes back to the original first summary of user "A".
- User "B" still show as the contributor. 

We should avoid this as it might pair a user with a summary that does not belong to him/her

**Comment by vlidholt** [comment]
Fixed.
