### ISSUE TITLE
Audio stops playing when launching Newsvoice app

### ISSUE THREAD

**Issue by natalieeden** [newsvoice/newsvoice#203]
Hello!

I’m listening to music on my iPhone SE using a podcast app called “Overcast.”  

When I launch Newsvoice, the audio stops playing and it only plays audio when I exit the Newsvoice app.  It doesn’t seem to be crashing—more like it’s pausing the audio as long as Newsvoice is open.

My phone is running iOS 12.3.1

**Comment by frog712** [comment]
VLC does this too. I would say that it's Newsvoice opening an audio channel which prompts the music app to pause, and/or the music app being designed to do so.

**Comment by vlidholt** [comment]
Fixed. Will be part of next release
