### ISSUE TITLE
Newsvoice Git Hub organization

### ISSUE THREAD

**Issue by skeptic17** [newsvoice/newsvoice#220]

**Comment by skeptic17** [comment]
Sorry for bad titles. Just getting acquainted with Git Hub.  

It might be helpful if there were separate sections for "issues", that is bugs and things like that, and "suggestions", that is ideas for improvement. Maybe "insights" which I see already exists could be used for that.

**Comment by vlidholt** [comment]
This is what the labels are for :) Going through the issues today, cleaning things up and prioritizing what's most pressing.

**Comment by skeptic17** [comment]
I understand. My suggestion was having a section for enhancements that was separate from issues (bugs). It is possible that "insights" could serve this role if you use it this way.
