### ISSUE TITLE
New login option

### ISSUE THREAD

**Issue by skeptic17** [newsvoice/newsvoice#221]
Thanks for implementing the non-Google log in option on the web site.  But I was thinking of something that doesn't tie to the phone either for people who really want to be anonymous. I realize there are issues of people creating multiple IDs and voting stories up, etc. but think it would be more helpful than not.

**Comment by vlidholt** [comment]
Having some kind of accountability improves the quality of the comments and contributions and makes it harder to create spam and bots. Feel free to reopen this issue if there is a concrete way we can do this without compromising the quality of the app.

**Comment by skeptic17** [comment]
It isn't clear to me how the google login creates any accountability. For that goal it would seem a login controlled by NV would actually be better.
