### ISSUE TITLE
"Stories" Tab missing

### ISSUE THREAD

**Issue by Digiguy** [newsvoice/newsvoice#223]
**System Reference**
- MAC OS 10.11.6 El Capitan
- Firefox 72.0.1 (64 Bit)

**Issue**
Missing Story Tab in Firefox
What I did notice is it looks like the stories are showing up in the **link** tab. I surmise these are stories as they do not have links.

![image](https://user-images.githubusercontent.com/97287/72637387-6d133980-391e-11ea-8235-7cbd40f076b9.png)

Errors on page via debugger in Firefox 72
![20200117_115017](https://user-images.githubusercontent.com/97287/72638068-e0697b00-391f-11ea-97f3-63878216810d.jpg)

**Comment by vlidholt** [comment]
Works as intended. New stories can currently only be approved by admins. This is because they also approve new news sources and sometimes new stories are added with only new sources.

Will add ability to add stories for mods in the future!
