### ISSUE TITLE
Android "Search" function not showing typed text

### ISSUE THREAD

**Issue by Digiguy** [newsvoice/newsvoice#225]
**Issue**
Typed text in the search tab is not showing up but does search for the actual typed text.

![Screenshot_20200117-125128](https://user-images.githubusercontent.com/97287/72642047-bf595800-3928-11ea-8d4c-3f1a997a86f0.jpg)

**System Reference**
- NewsVoice 2.0.11
- Android Ver/ (see below)
![Screenshot_20200117-125906_Settings](https://user-images.githubusercontent.com/97287/72642375-68a04e00-3929-11ea-9665-de90624bcab0.jpg)

**Comment by skeptic17** [comment]
> 
Note: text is visible in regular mode. The problem is in "dark theme" where the text is white on white.
@skeptic

> 
> **Issue**
> Typed text in the search tab is not showing up but does search for the actual typed text.
> 
> ![Screenshot_20200117-125128](https://user-images.githubusercontent.com/97287/72642047-bf595800-3928-11ea-8d4c-3f1a997a86f0.jpg)
> 
> **System Reference**
> 
>     * NewsVoice 2.0.11
> 
>     * Android Ver/ (see below)
>       ![Screenshot_20200117-125906_Settings](https://user-images.githubusercontent.com/97287/72642375-68a04e00-3929-11ea-9665-de90624bcab0.jpg)

**Comment by skeptic17** [comment]
Note: this bug is only in 'dark theme' where text is white on white. In regular mode the text is visible.  @skeptic

**Comment by vlidholt** [comment]
Fixed (will be part of next release)
