### ISSUE TITLE
Saved stories not showing time in months

### ISSUE THREAD

**Issue by Digiguy** [newsvoice/newsvoice#227]
**Issue**
Saved summaries older than 4 weeks show **_0 months_** Saved Items up to and including 4 weeks show properly as the number of weeks, but once it flips to counting months, it resets to 0.

![Screenshot_20200117-214628](https://user-images.githubusercontent.com/97287/72658940-30bef800-3975-11ea-81a1-21986b75dcc5.jpg)

**Reference System**
Samsung G9+
![Screenshot_20200117-125906_Settings](https://user-images.githubusercontent.com/97287/72658899-a70f2a80-3974-11ea-9a33-3d8e2010a84c.jpg)

**Comment by vlidholt** [comment]
Fixed, will be part of next app update!
