### ISSUE TITLE
Numbering of summary rejection not matching between sent and recieved

### ISSUE THREAD

**Issue by Digiguy** [newsvoice/newsvoice#228]
When an article is rejected for **_Spelling and Grammar_** the submitting user receives a notice that the reason **_Avoid Bias_**

Bonus issue is the screen that displays the rejection is yellow with white text. Very hard to read.
The attached screen shot shows a submission by BK and rejected numerous times by Skeptic due to the confusion it became an issue of miss understanding. 

My feeling is that if people are getting this kind of "bias rejection" and they are not being biased, they can take it personally as clearly it was not bias that was the issue. This can directly effect user engagement and is a serious problem as spelling and grammar are a go to reason for a majority of issues of rejection, but now it seems users may be seeing bias as the reason for their rejection....

![Screenshot_20200117-110132](https://user-images.githubusercontent.com/97287/72667257-10278a00-39d7-11ea-8c63-7498cb81da6a.jpg)

**System Reference**
Galaxy S9+
![Screenshot_20200117-125906_Settings](https://user-images.githubusercontent.com/97287/72667275-4402af80-39d7-11ea-8480-dbd16c854b54.jpg)

**Comment by vlidholt** [comment]
Fixed, will be part of next app release
