### ISSUE TITLE
New and Top Ratings are not understandable -US News Section in particular

### ISSUE THREAD

**Issue by Digiguy** [newsvoice/newsvoice#229]
### **Issue**
In the example below, It is hard to understand why something is **_top voted_** and another is **_New_** I have checked the website, and I am assuming the same database and calculations are used. 

It is hard to understand what type of weighting or system is at play here. I do not see that one really makes any more sense than another. Some other sections like world do have what appears to make sence in terms of time in the **_New_** section, but in the **_Top_** There must be some weighting given between time-comments-up vote as it is not making sense why some are down in the list but very popular. See insert.
![20200118_124357-COLLAGE](https://user-images.githubusercontent.com/97287/72669671-20009780-39f2-11ea-8ee9-6b311396e25b.jpg)

### **Suggestion**
More filters are needed at the top of the app and webpage
- **Top Comments Sort button** - This would engage users to interact with the most active stories. It could reset daily or weekly. Those features as a pay or future upgrade.
(It should be usage tracked to see if further granulation of it into **_All-time Top sort commented_**, **_Hot Takes (Most Active=upvote+comment total)_**, filtering options could be future added or pay features)

- Website main page has plenty of room (as noted beside to offer filter buttons for **Commented sort**, **Most Active**
![image](https://user-images.githubusercontent.com/97287/72669722-a74e0b00-39f2-11ea-9846-ca054edb9b53.png)

### **System Reference**
![Screenshot_20200117-125906_Settings](https://user-images.githubusercontent.com/97287/72669675-41fa1a00-39f2-11ea-9d34-26aa07bfc433.jpg)

**Comment by vlidholt** [comment]
The top section uses a combination of when the story is added and how many upvotes it have. Similar to how Reddit works. Will add a point to the upcoming FAQ page that describes the system and provides code for how the ranking is done.
