### ISSUE TITLE
Aggregate points not getting updated (Issue noted by @Porcus)

### ISSUE THREAD

**Issue by fareem1** [newsvoice/newsvoice#231]
Update: Graph getting updated with activity. But aggregate points not increasing
(I just noticed that I am no longer getting any points for my edits, links, summaries, etc.
I made a lot of edits today and happened to notice that my total points hasn't changed in at least a week, possibly longer)

**Comment by Digiguy** [comment]
I too had noticed very few points added but the 'graph' still working... then at midnight on the 20th. The graph stopped working as well. I did the upgrade in the afternoon, and did reboot my phone in the evening.
Android S9+ (same as the other issues)

**Comment by vlidholt** [comment]
Fixed.
