### ISSUE TITLE
Edit flow on APPS. 

### ISSUE THREAD

**Issue by BreakingBubbles** [newsvoice/newsvoice#24]
When entering the edit flow on the apps, a screen appears asking to join as volunteer, even though the use is already registered as one. The screen should instead be: If already a volunteer --> explain that editing only possible on web for now, plus link to edit stage of the same news item on web. If not a volunteer, display existing screen, PLUS explain editing only possible on web.

**Comment by vlidholt** [comment]
This is now fixed!
