### ISSUE TITLE
Stories appearing without links

### ISSUE THREAD

**Issue by skeptic17** [newsvoice/newsvoice#243]
@Avi reported on Slack on 02/02/2020 that the story on the palindromic date appeared with no links.  It has them now.  But I've also seen that happen.  I'll take a screen shot if I see it again.

**Comment by fareem1** [comment]
Adding to what @skeptic17 mentioned, stories are showing up without being approved. Attaching screenshots below as a reference

1. As it appeared (without approval)
<img width="1328" alt="Screen Shot 2020-02-04 at 07 53 52" src="https://user-images.githubusercontent.com/40382741/73721206-08c8e600-4724-11ea-933f-406f0f8191dc.png">

2. After approving the links
<img width="964" alt="Screen Shot 2020-02-04 at 07 55 11" src="https://user-images.githubusercontent.com/40382741/73721211-0cf50380-4724-11ea-8710-4ca145d5029d.png">

[](url)

**Comment by avikhait** [comment]
@skeptic17: you've linked the wrong Avi. The rest is correct.

**Comment by avikhait** [comment]
Seeing this again, e,g. 
https://newsvoice.com/i/4177008
https://newsvoice.com/i/4176902

**Comment by vlidholt** [comment]
Fixed today. Please reopen if it happens to any new stories.
