### ISSUE TITLE
Different problem with Bloomberg links

### ISSUE THREAD

**Issue by skeptic17** [newsvoice/newsvoice#260]
Bloomberg links point to the correct story, but the headline is "Are you are robot?" presumably because of a captcha needed to access site.

This is different from #259 because the link does point to correct story. To fix it we just need to edit the headline.
https://newsvoice.com/i/4189786
![image](https://user-images.githubusercontent.com/59395538/74249350-04b63e80-4cb7-11ea-8006-3c289c4c8ad8.png)

**Comment by vlidholt** [comment]
Fixed, will only affect new stories though. Will be part of next update.
