### ISSUE TITLE
Add pop ups in the apps asking for reviews

### ISSUE THREAD

**Issue by BreakingBubbles** [newsvoice/newsvoice#27]

**Comment by BreakingBubbles** [comment]
There is maybe a better way (bit more work) and include the review box natively as part of the product. It could be inserted in the news feed so does not disrupt experience. Check this link. It has given good results https://medium.com/circa/the-right-way-to-ask-users-to-review-your-app-9a32fd604fca

**Comment by vlidholt** [comment]
Implemented it like the link suggested. Much more pleasant than a popup. Will be part of 1.1.17.
