### ISSUE TITLE
Notification on link submission not consistent

### ISSUE THREAD

**Issue by fareem1** [newsvoice/newsvoice#270]
As noted by a user:
I submitted another link for that article (
https://www.independent.co.uk/news/philip-haney-dhs-homeland-security-obama-administration-a9353806.html ) and was shortly told that my edit was rejected because the article already had a summary.  **I had not edited the summary, I only added a link.**

Tried it ay my end with a couple of stories via the app, did not get a notification

**Comment by vlidholt** [comment]
Perhaps he hit the wrong button and submitted the story instead of the link?
