### ISSUE TITLE
Irregularities in the Links tab for Mods

### ISSUE THREAD

**Issue by fareem1** [newsvoice/newsvoice#276]
The links tab for some of the mods seems to be showing the Stories tab (noted by Ryan M)

![Screenshot_2020-03-05-17-10-52](https://user-images.githubusercontent.com/40382741/76024466-7cc8fa80-5f2b-11ea-9de2-f9b65794483e.png)

**Comment by vlidholt** [comment]
Fixed, will be part of next update
