### ISSUE TITLE
Add News Stories Timing prompt

### ISSUE THREAD

**Issue by Erik-Sandberg** [newsvoice/newsvoice#48]
Hi,

First post here so be gentle. When I post news stories the prompt tells me that it will take a few minutes to appear, but it's taking significantly longer - my last one over half an hour. Perhaps there is a way to also notify the contributor when their story has appeared in the feed, too, so they can track back the URL and add a summary if they'd like.

Thanks,
Erik.

**Comment by vlidholt** [comment]
It gets added when there are enough votes to show it (you can get these votes from the moderator interface). Although, this process need to be more clear. Adding this to the next milestone to fix together with other issues regarding adding news.

**Comment by vlidholt** [comment]
Text is updated, will be part of next push.
