### ISSUE TITLE
Merging stories is causing a bug in comments counter

### ISSUE THREAD

**Issue by Erik-Sandberg** [newsvoice/newsvoice#56]
![screen shot 2018-01-26 at 09 27 58](https://user-images.githubusercontent.com/35601186/35434734-10871d48-0280-11e8-8f1f-fc6de52553b7.png)

I tried to merge two stories this morning, when I did - into a story which had a comment - the comment remained, but the counter reset itself back to zero. here is the link: https://newsvoice.com/i/2146119

**Comment by vlidholt** [comment]
Fixed, part of next update
