### ISSUE TITLE
"this summary is claimed" tag should disappear once the summary is approved

### ISSUE THREAD

**Issue by BreakingBubbles** [newsvoice/newsvoice#92]
I guess this might be tied in with the functionality of being able to vote different summaries. 
We do not want people to fell discouraged from adding their own summary.

**Comment by vlidholt** [comment]
This is not a huge issue as the claimed label is automatically removed after 15 minutes. I'm moving this to the next milestone.

**Comment by vlidholt** [comment]
Fixed. Will be uploaded tomorrow.
